openapi: 3.1.0
info:
  title: Historical News API
  description: Allows you to retrieve historical news using a filter.
  version: 0.1.0
servers:
  - url: https://newswareapi.encypherstudio.com/v1/api
paths:
  /news:
    post:
      summary: Get news
      description: Returns a page of news that match the given filter. Works also with GET method.
      security:
        - ApiKeyHeader: []
        - ApiKeyQuery: []
      requestBody:
        description: |
          Used to filter news by publication time, tickers and a query.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsFilter'
      responses:
        200:
          description: A JSON page of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      description: |
                        Sequential id generated by Newsware
                      example: 24
                      type: integer
                    headline:
                      description: Headline of the news
                      example: |
                        Press Release: Capgemini to acquire FCC division of Exiger, to expand its Financial Crime Compliance advisory, analytics and managed services capabilities
                      type: string
                    body:
                      description: Body of the news
                      example: |
                        <?DOCTYPE html?><html><head><title>Press Release: Capgemini to acquire FCC division of Exiger, to expand its Financial Crime Compliance advisory, analytics and managed services capabilities</title></head><body><div><h1>Press Release: Capgemini to acquire FCC division of Exiger, to expand its Financial Crime Compliance advisory, analytics and managed services capabilities</h1><p class="newswire-article-time">September 8, 2023 06:30:00 UTC</p></div><div><div><p>Media relations:</p><p>Sam Connatty</p><p>Tel.: +44 (0)370 904 3601</p><p>https://www.globenewswire.com/Tracker?data=gC9eNIS97ojwrII3F5DBubYJmHo0vP3wqy-iWwztFoC3nohKKt4LXYYMd2AGicdR-2T8Vfm7AdAukinHOOXjIcIOV0m3OyMCr3hrdS8_VY9YvCf11Dce8th5an6-2C-g sam.connatty@capgemini.com</p><p>Investor relations:</p><p>Vincent Biraud</p><p>Tel.: +33 1 47 54 50 87</p> With its strong 55-year heritage and deep industry expertise, Capgemini is trusted by its clients to address the entire breadth of their business needs, from strategy and design to operations, fueled by the fast evolving and innovative world of cloud, data, AI, connectivity, software, digital engineering and platforms. The Group reported in 2022 global revenues of EUR22 billion.</p><p>Get The Future You Want | www.capgemini.com</p><p>Attachment</p><pre>-- 09_08_Capgemini to acquire FCC division of Exiger &#xA;      https://ml-eu.globenewswire.com/Resource/Download/718ae574-00df-4c2a-90e4-e8b4a0268867</pre><p>(END) Dow Jones Newswires</p><p>September 08, 2023 02:30 ET (06:30 GMT)</p></div></div><div><div><strong>s.DJ CAP.FR CGEMY</strong></div><div><strong>Article id:  | Exchange:  | Region:</strong></div><div><strong>Industry Codes:  | Category Codes:</strong></div></div></body></html>
                      type: string
                    tickers:
                      type: array
                      items:
                        type: string
                      description: A list of tickers related to the news
                      example: [ APPL, HSBC ]
                    source:
                      description: Source of the news
                      $ref: '#/components/schemas/Source'
                      example: SEC
                    publicationTime:
                      type: string
                      description: Time of publication
                      example: 2023-09-12T03:30:00Z
                    receivedTime:
                      type: string
                      description: Time the news was received by Newsware
                      example: 2023-09-12T03:30:02.192731316Z
                    creationTime:
                      type: string
                      description: Time the news was indexed into the Newsware database
                      example: 2023-09-12T03:30:02.351817973Z
                    ciks:
                      type: array
                      items:
                        type: integer
                      description: (Only valid for SEC filings) CIKs associated to the SEC filing
                      example: [ 1375793, 1692705 ]
                    link:
                      type: string
                      description: (Only valid for SEC filings) Official SEC link to filing
                      example: https://www.sec.gov/Archives/edgar/data/1692705/000110465923099095/0001104659-23-099095-index.htm
        403:
          description: Api key was not set or is not associated to any user.
        default:
          description: Unexpected error

components:
  securitySchemes:
    ApiKeyHeader:
      type: apiKey
      in: header
      name: X-API-KEY
    ApiKeyQuery:
      type: apiKey
      in: query
      name: apiKey
  schemas:
    NewsFilter:
      description: |
        Used to filter news by publication time, tickers and a query.
        
        Example:
        ```json
        {
          "query": {
            "and": [
              {"text": "bitcoin", "searchHeadline": "true"},
              {"text": "bull run", "searchBody": "true", "ignore": "true"}
            ]
          },
          "tickers": ["APPL", "BMW", "BTC"],
          "ciks": [1805719, 1557593],
          "sources": ["DJ", "AR", "PZ", "PN", "BW", "SEC", "HS"],
          "pagination": {"limit": 10, "page": 2},
          "publishedBefore": 1695102611,
          "publishedAfter": 0
        }
        ```
      properties:
        pagination:
          $ref: '#/components/schemas/NewsPagination'
        publishedBefore:
          description: UNIX timestamp. Blank or less than 1 to ignore.
          $ref: '#/components/schemas/NewsTimeLimit'
        publishedAfter:
          description: UNIX timestamp. Blank or less than 1 to ignore.
          $ref: '#/components/schemas/NewsTimeLimit'
        tickers:
          description: A list of tickers. If the ticker exists in the news, it will be fetched.
          type: array
          items:
            type: string
        ciks:
          description: A list of CIKs. If the ticker exists in the SEC filing, it will be fetched.
          type: array
          items:
            type: integer
        query:
          $ref: '#/components/schemas/NewsQuery'
        sources:
          description: A list of sources. Only news from theses sources will be fetched. If empty, all sources are fetched.
          type: array
          items:
            $ref: '#/components/schemas/Source'
      example:
        query:
          and:
            - text: bitcoin
              searchHeadline: true
            - text: bull run
              searchBody: true
              ignore: true
          tickers:
            - APPL
            - BMW
            - BTC
          ciks:
            - 1805719
            - 1557593
          sources:
            - DJ
            - AR
            - PZ
            - PN
            - BW
            - SEC
            - HS
          pagination:
            limit: 10
            page: 2
          publishedBefore: 1695102611
          publishedAfter: 0
    NewsTimeLimit:
      description: A UNIX timestamp. If set to 0 or less, the limit is not applied.
      type: integer
    NewsPagination:
      description: Describes how many items per page and what page to fetch.
      properties:
        page:
          description: Current page, the first page is 1.
          minimum: 1
          default: 1
          type: integer
          required: true
        limit:
          description: Number of items per page.
          type: integer
          minimum: 1
          maximum: 10000
          default: 10
          required: true
    NewsQuery:
      description: |
        Filter for news. Properties are mutually exclusive, only one of "and", "or" or "text" can be set.
        
        Example, search for news that contain either "bitcoin" AND "bull run", OR "dollar", in the headline:
        ```json
        {
          "or": [
            {
              "and": [
                {"text": "bitcoin", "searchHeadline": "true"},
                {"text": "bull run", "searchHeadline": "true"}
              ]
            },
            { "text": "dollar", "searchHeadline": "true"}
          ]
        }
        ```
      properties:
        and:
          type: array
          description: "A list of queries that wil be joined by an \"and\" condition. It can contain a {text: ...} filter, or nested conditions in the form of {and: ...} or {or: ...}"
          items:
            $ref: '#/components/schemas/NewsQuery'
          example:
            - text: "btc"
              searchHeadline: "true"
            - and:
                - text: "bitcoin"
                  searchBody: "true"
                - text: "bull run"
                  searchBody: "true"
        or:
          type: array
          description: "A list of queries that wil be joined by an \"or\" condition. It can contain a {text: ...} filter, or nested conditions in the form of {and: ...} or {or: ...}"
          items:
            $ref: '#/components/schemas/NewsQuery'
          example:
            - text: "btc"
              searchHeadline: "true"
            - or:
                - text: "bitcoin"
                  searchBody: "true"
                - text: "bull run"
                  searchBody: "true"
        text:
          type: object
          description: Describes a term to look for and where to look for it.
          properties:
            text:
              type: string
              description: Text to look for in the news records
              example: bitcoin
            searchBody:
              type: boolean
              description: Whether to search for the text in the body or not
              example: true
            searchHeadline:
              type: boolean
              description: Whether to search for the text in the headline or not
              example: true
            ignore:
              type: boolean
              description: Whether to ignore news that contain the text
              example: false
          example:
            text: "bull run"
            searchBody: "true"
            searchHeadline: "false"
            ignore: "true"
    Source:
      type: string
      enum:
        - DJ
        - AR
        - PZ
        - PN
        - BW
        - SEC
        - HS